-- Agregar ADMIN_FINANZAS al ENUM rol de la tabla usuarios
ALTER TABLE usuarios
  MODIFY COLUMN rol
    ENUM('ADMIN','JEFE_ESTUDIOS','DOCENTE','JEFE_CURSO','CURSANTE','ADMIN_FINANZAS')
    DEFAULT NULL;
